Group18_WasteNotWantNot/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_page#home'

  get '/help', to: 'static_page#help'
  get '/about', to: 'static_page#about'
  get '/contact', to: 'static_page#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/affiliated', to: 'static_page#affiliated'
  resources :users

end

Group18_WasteNotWantNot/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Group18_WasteNotWantNot/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }


end

Group18_WasteNotWantNot/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

Group18_WasteNotWantNot/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
  end
end

Group18_WasteNotWantNot/app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def affiliated
  end
end

Group18_WasteNotWantNot/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      flash[:success] = "Welcome to WNWN!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

Group18_WasteNotWantNot/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Waste Not Want Not"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end
end

Group18_WasteNotWantNot/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
end

Group18_WasteNotWantNot/app/helpers/static_page_helper.rb
module StaticPageHelper
end

Group18_WasteNotWantNot/app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
 def gravatar_for(user)
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
   image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

Group18_WasteNotWantNot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    

  <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
    <![endif]-->
  </head>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  <%= yield %>


</html>

Group18_WasteNotWantNot/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Group18_WasteNotWantNot/app/views/static_page/about.html.erb
<% provide(:title,"About")%>
    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

Group18_WasteNotWantNot/app/views/static_page/affiliated.html.erb
<% provide(:title, "Affiliated Page") %>

<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="home.html">Waste Not Want Not</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
				<li class="active"><a href="#">Home</a></li>

				<li><a href="profile.html"><span class="glyphicon glyphicon-user"></span>Profile</a></li>
				<li><a href="planner.html"><span class="glyphicon glyphicon-calendar"></span>Meal Planner</a></li>
				<li><a href="achievement.html"><span class="glyphicon glyphicon-queen"></span>Achievements</a></li>

				</ul>
				<ul class="nav navbar-nav navbar-right">
				<li><a href="logout.html"><span class="glyphicon glyphicon-log-out"></span>Sign Out</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="row"><br></div>

	<div class="row title"><h1>Our partner apps</h1></div>
	<div class="row"><br></div>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
      <%= link_to image_tag("foodnotes.png", alt: "Food Note",class: "foodnotes") %>
			<h2>Keep track of your food waste, in terms of... MONEY</h2>
      <hr>
      <h1> iPicky </h1>
			<h2>Use the grouped list when planning avoid buying food that no one wants to eat.</h2>
		</div>
	</div>
</body>

Group18_WasteNotWantNot/app/views/static_page/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

Group18_WasteNotWantNot/app/views/static_page/help.html.erb
<% provide(:title,"Help")%>
    <h1>Help</h1>

Group18_WasteNotWantNot/app/views/static_page/home.html.erb
<body class="home">
  <header>
        <div class="container">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home",   root_path %></li>
              <li><%= link_to "Help",   help_path %></li>
              <li><%= link_to "Log in", login_path %></li>
            </ul>
          </nav>
        </div>
      </header>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="center">
      <h1>Save your food with our app</h1>

      <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>
    </div>
  <!--  <%= debug(params) if Rails.env.development? %>-->
  </div>
</body>

Group18_WasteNotWantNot/app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<body>
  <header>
        <div class="container">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home",   root_path %></li>
              <li><%= link_to "Help",   help_path %></li>
              <li><%= link_to "Log in", login_path %></li>
            </ul>
          </nav>
        </div>
      </header>

      <!--Logo-->

      <div class="col-xs-12 img" >
        <%= image_tag("logo.png", alt: "Waste Not Want Not",id: "logo_big") %>
      </div>

      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>


      <!--link back to sign in-->
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2 center"><br>Already A Member?
          <%= link_to "Click here",   login_path %></br>
        </div>
      </div>

</body>

Group18_WasteNotWantNot/app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<body>
  <nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="home.html">Waste Not Want Not</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">

				<li class="active"><a href="#">Home</a></li>
				<li><a href="profile.html"><span class="glyphicon glyphicon-user"></span>Profile</a></li>
  			<li><a href="planner.html"><span class="glyphicon glyphicon-calendar"></span>Meal Planner</a></li>
				<li><a href="achievement.html"><span class="glyphicon glyphicon-queen"></span>Achievements</a></li>

        <li><%= link_to "Affliated Page",affiliated_path%></li>

				</ul>
				<ul class="nav navbar-nav navbar-right">
				<li><a href="logout.html"><span class="glyphicon glyphicon-log-out"></span>Sign Out</a></li>
				</ul>
			</div>
		</div>
	</nav>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
    <div class="container">
        <div class="col-xs-12"><br></div>
        <div class="row">
                <a href="#" class=" btn btn-info btn-lg col-xs-12">
                  <span class="glyphicon glyphicon-calendar"></span> Meal Planner
                </a>
        </div>
        <div class="col-xs-12"><br></div>
        <div class="row">
                <a href="#" class="btn btn-info btn-lg col-xs-12">
                  <span class="glyphicon glyphicon-star-empty"></span>Achievement
                </a>
        </div>
        <div class="col-xs-12"><br></div>
        <div class="row">
            <a href="#" class="btn btn-info btn-lg col-xs-12">
              <span class="glyphicon glyphicon-bookmark"></span> Affiliated Page
            </a>
        </div>
        <div class="col-xs-12"><br></div>
        <div class="row">
            <a href="#" class="btn btn-info btn-lg col-xs-12">
              <span class="glyphicon glyphicon-user"></span> Profile
            </a>
        </div>
    </div>
  </div>
</body>